name: ThinkBayes2Book
channels:
  - conda-forge
  - fastai
  - nodefaults
dependencies:
  - arviz=0.11.0
  - cycler
  - empiricaldist
  - fastai::fastdoc
  - ghp-import
  - html5lib
  - jupyter
  - jupyter-book
  - jupyter_nbextensions_configurator
  - lxml
  - matplotlib
  - mkl-service
  - nbconvert
  - nbmake
  - numpy
  - pandas
  - pandoc<2.3
  - pip
  - pymc3
  - pytables
  - pytest
  - python>=3.6
  - python-graphviz
  - scipy
  - seaborn
  - statsmodels
  - xlrd
